# The URL the site will be built for
base_url = "https://baccaert.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# The title of the website
title = "Tim Baccaert"

taxonomies = []

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
keywords = ""
author = "Tim Baccaert"
year = 2024
job = "Ph.D. Student"
lab = "Software Languages Lab"
department = "Department of Computer Science"
university = "Vrije Universiteit Brussel"
email = "tim.baccaert@vub.be"
address = "Pleinlaan 2, 1050 Brussels, Belgium"
github = "timplication"
orcid = "0000-0002-7115-204X"
